# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sports Updates' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sports Updates

 pod 'Alamofire', '~> 4.0'
pod "DropDown"
pod 'MBProgressHUD', '~> 1.2.0'
pod 'FSCalendar'


end
